spring:
  application:
    name: ordering
  datasource:
    url: jdbc:postgresql://localhost:5432/ordering
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/ordering
    locations: classpath:db/migration,classpath:db/testdata
    user: postgres
    password: postgres

algashop:
  integrations:
    shipping:
      provider: RAPIDEX
    rapidex:
      url: http://localhost:8780
    product-catalog:
      url: http://localhost:8780
  free-shipping:
    min-basic-loyalty-points: 200
    min-basic-sales-amount-in-year: 2
    min-premium-loyalty-points: 2000