create table customers (
    id uuid not null,
    archived boolean,
    birth_date date,
    loyalty_points integer,
    promotion_notifications_allowed boolean,
    archived_at timestamp(6) with time zone,
    last_modified_at timestamp(6) with time zone,
    registered_at timestamp(6) with time zone,
    version bigint,
    created_by uuid,
    last_modified_by uuid,
    address_city varchar(255),
    address_complement varchar(255),
    address_neighborhood varchar(255),
    address_number varchar(255),
    address_state varchar(255),
    address_street varchar(255),
    address_zip_code varchar(255),
    document varchar(255),
    email varchar(255),
    first_name varchar(255),
    last_name varchar(255),
    phone varchar(255),
    primary key (id)
);
